### ISSUE TITLE
yarn add -WD @storybook/addon-viewport

### ISSUE THREAD

**Issue by lkraav** [web-padawan/aybolit#10]
For evaluating / testing component implementation quality across device categories, this addon looks relatively useful.

https://github.com/storybooks/storybook/tree/master/addons/viewport

Your thoughts?

**Comment by web-padawan** [comment]
I have considered various Storybook addons (storysource, viewport etc) but using them will make building a Storybook a bit longer, it is already taking around 5 seconds on my nachine. 

At this point, I don't plan to build any components for complex layouts, so I don't see any benefit in using this particular addon for Aybolit. I might reconsider that in future though.
