### ISSUE TITLE
Using different file and setup structure for packages

### ISSUE THREAD

**Issue by chanar** [web-padawan/aybolit#13]
1) Currently, the lit components are compiled with storybook webpack configuration. In case I would like to run webpack-serve from the current lit element project (that I will bring over to packages/my-lit-project), where should I do it? Do you recommend creating custom commands to root level package.json? Also what about production builds. Would you build them in /dist/package/package-name/bundle.js or /packages/package-name/dist/?

2) Do you have specific recommendations to follow on package file structure. For example my project currently looks something like this like this:

```
/src/components/component-name.js
/src/components/component-name.scss
/src/theme/vaadin/vaadin-button.js
/src/theme/vaadin/vaadin-button.scss
/src/redux/
/templates/file.html (that put together initial component setups)

webpack-configs.js
netlify.toml
babel.config.js
```

**Comment by web-padawan** [comment]
Sorry about the long delay with answer. Is the question still valid?

Regarding file structure, it's up to the user. And note that Aybolit is not following any patterns used by Vaadin components, as it's not related to them.

**Comment by lkraav** [comment]
@chanar latest thoughts on this subject?

**Comment by web-padawan** [comment]
Closing per above comment and because it's not an issue of the library itself but tooling question.
