### ISSUE TITLE
Including scss mixins

### ISSUE THREAD

**Issue by chanar** [web-padawan/aybolit#16]
With aybolit setup, where should I include scss mixins/variables that are being used throughout  multiple packages?

Before I used `sass-resources-loader` in webpack to load the mixins to all scss included.

**Comment by web-padawan** [comment]
In the monorepo, everything is a package. So, I would recommend placing Sass mixins to a separate package, which could be marked as `"private": true` in case there is nothing to publish to npm.

See for example how `mwc-button` web component [imports SCSS for icon](https://github.com/material-components/material-components-web-components/blob/f362fc51c87db64bbd686fa53325811f1fb33bec/packages/button/src/mwc-button.scss#L19) from the other package.

**Comment by chanar** [comment]
But how would you separate it from the file structure that the current ./scripts/build-styling.sh is doing?

/scss -> /components/styles

Should I use it only on certain packages then?

I also have now
/packages/app1/scss/global-styles-for-app1
/packages/app2/scss/gloval-styles-for-app2

that needs to be compiled and included in /packages/app2/src/index.js

There is no components for them as all components are in /components.

Is it safe to say that the structure you have built is only for this specific /packages/* setup? The aybolit idea is to be something like Vaadin but much more easily extendable as seen in /core where the base has been set and all other packages extend it.

**Comment by chanar** [comment]
Closing this issue as we have found an agreement of file structures for now
