### ISSUE TITLE
Autoprefixer

### ISSUE THREAD

**Issue by lkraav** [web-padawan/aybolit#27]
Heya. With https://github.com/postcss/autoprefixer I wonder if a PostCSS build stack would make sense to strive towards, after all.

@web-padawan do you have any objections to Autoprefixer in general?

What about PostCSS? (while still keeping `dart-sass` central, as currently is, at least for now)

**Comment by web-padawan** [comment]
Autoprefixer is generally not needed for modern browsers supported by Aybolit, except for certain properties like `user-select` and `-webkit-appearance`, and I prefer listing these explicitly.

Scss is just a personal preference. I'm ok with PostCSS too, just don't know if it would improve compilation time significantly (`dart-sass` should be fast, too).

**Comment by lkraav** [comment]
https://github.com/WordPress/gutenberg/issues/14801 very interesting in-depth discussion wrt SASS vs PostCSS

@mor10 quote

> From my perspective this is about setting the stage for future development. Sass sits firmly anchored in the past and old best-practices. Building it into tooling at this stage suggests to users that Sass is a viable path forward. That would be unfortunate since modern CSS with the assistance of PostCSS is the official path forward for the web platform. Building in further reliance on Sass at this point holds us back from what's happening elsewhere.

**Comment by mor10** [comment]
My recommendation is using PostCSS with [`postcss-preset-env`](https://github.com/csstools/postcss-preset-env). It gives you a solid platform for both future-forward and bleeding edge features, _and_ proper backwards compat when needed.

**Comment by web-padawan** [comment]
Thanks for the input, but please keep in mind the following:

1. This project doesn't need the various capacities of PostCSS. What we really need here are variables (used in combination with custom CSS properties) and loops.

2. Keeping the `.scss` source makes it clear that these files are not supposed to be used directly.

**Comment by web-padawan** [comment]
I'm back from my vacation and doing some cleanup here, so let me close this issue per above comment. You can switch to [precss](https://github.com/jonathantneal/precss) in your projects if you wish, but I'm going to keep Sass for now.
